# Hyprlock — lock screen config

background {
    monitor =
    path = /home/arham/Pictures/wallpaper/macos-monterey-wwdc-21-stock-dark-mode-5k-6016x6016-5585.jpg
    blur_passes = 3
    blur_size = 6
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    outer_color = rgba(87ceebee)
    inner_color = rgba(1a1a1aee)
    font_color = rgb(d0d0d0)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    halign = center
    valign = center
    position = 0, -20
}

label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = JetBrains Mono
    color = rgba(d0d0d0ee)
    halign = center
    valign = center
    position = 0, 100
}
