[ids]
* 

[main]

# Colemak-DH Wide remap (ANSI)
# Left hand
` = rightcontrol
q = q
w = w
e = f
r = p
t = b
a = a
s = r
d = s
f = t
g = g
z = x
x = c
c = d
v = v
[ = semicolon
] = apostrophe

# Right hand
b = z
u = j
i = l
o = u
p = y

j = m
k = n
l = e
semicolon = i
apostrophe = o

m = k
comma = h
dot = ,
slash = .

n = k



# Ergonomic mods
capslock = overload(control, esc)
rightcontrol = layer(fn)
\ = leftalt 
leftcontrol = layer(numbers)
leftmeta = leftmeta
leftalt = layer(nav)
rightalt = layer(symbols) 
leftshift = oneshot(shift)
rightshift = oneshot(shift)

# Space and arrows unchanged
space = space
up = up
down = down
left = left
right = right

[symbols]
# Example symbol layer
# upper row
tab = | 
q = `
w = (
e = )
r = [
t = ?
i = ]
o = {
p = }

# home row
capslock = / 
a = !
s = +
d = -
f = *
h = |
g = %
k = =
l = ^
semicolon = $
apostrophe = ;

# lower row
leftshift = \ 
z = &
x = #
c = "
v = @

# space
space = _

[nav]
w = layer(numbers)
e = leftalt
r = leftcontrol
i = rightalt
o = rightcontrol
p = rightshift

space = tab

a = leftmeta 
s = leftshift
f = leftcontrol
d = layer(second_nav) 

k = down
l = up
j = left
semicolon = right
apostrophe = backspace

comma = M-tab
m = delete

[numbers]
#Numbers layer

space = 0
8 = 7
9 = 8
0 = 9

k = 1
l = 2
semicolon = 3
i = 4
o = 5
p = 6 

j = /
u = *
[ = .
comma = \
# apostrophe = -
# [ = +
# comma = /
# dot = *
# slash = . 

[fn]
a = f1
s = f2
d = f3
f = f4
k = f5
l = f6
semicolon = f7
apostrophe= f8
z = f9
x = f10
c = f11
v = f12

[second_nav]
j = h 
k = j 
l = k
semicolon = l

u = home 
i = pagedown 
o = pageup
p = end
