wallpaper {
    monitor = eDP-1
    path = /home/arham/Pictures/wallpaper/mercedes_car.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/arham/Pictures/wallpaper/mercedes_car.jpg
    fit_mode = cover
}

splash = false
