-- Generated by nwg-displays on 2026-08-14 at 18:09:59. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.01",
    position = "0x0",
    scale = 1.5
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "1280x0",
    scale = 1.0
})
